// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fufsrkipjwyexjvwpnsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1ZnNya2lwand5ZXhqdndwbnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODEyNjcsImV4cCI6MjA2MDU1NzI2N30.rS-_hHrtqh6s77XJov7Ym8JuWJpktYXakNFVT_1TXQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);